### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by aliafshany** [inPhraZ/VC-Downloader#1]
سلام
امیدوارم که خوب باشید.

میخواستم بدونم که این افزونه صرفا فیل زیپ کلاس هارو دانلود میکنه؟

ممنونم

**Comment by inPhraZ** [comment]
سلام
بله

**Comment by inPhraZ** [comment]
> سلام امیدوارم که خوب باشید.
> 
> میخواستم بدونم که این افزونه صرفا فیل زیپ کلاس هارو دانلود میکنه؟
> 
> ممنونم

سلام
بله
